# Generated by Django 3.2.11 on 2022-01-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220113_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlationresult',
            name='p_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correlationresult',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
