# Generated by Django 3.2.11 on 2022-01-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220113_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlationresult',
            name='p_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='correlationresult',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
